main/urls.py
from django.contrib import admin
from django.shortcuts import render, redirect
from django.urls import path
from . import views

app_name = 'main'
urlpatterns = [
    path('',views.index,name='index'),
    path("download/",views.download_video,name='download'),
    path("cut/",views.cut_video,name="cut"),
    path("result/",views.result,name='result'),
    path("about/",views.about,name='about')
]

uofthacks/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
# Create your views here.
import urllib.request
import os
from cut_core.cut import main


import shutil
from moviepy.editor import VideoFileClip, concatenate_videoclips


def index(request):
    return render(request,'home.html')


def download_video(request):
    url_link = request.POST["urlname"]
    urllib.request.urlretrieve(url_link, './static/video.mp4')
    return render(request,"success.html")


def cut_video(request):
    os.chdir("C:\\pyproj\\uofthacks\\static")
    os.system('ffmpeg -i video.mp4 -af silencedetect=noise=-20dB:d=0.2 -f null - 2> output.txt')
    # read txt method one
    f = open("./output.txt")
    f_out = open('./out.txt', 'w')
    line = f.readline()
    while line:
        if "silence_end" in line:
            haha = line.split("silence_end:")[1]
            haha3 = haha.split(" |")[0]
            haha2 = haha.split("silence_duration: ")[1]
            haha4 = haha2.split("\n")[0]

            print(haha3 + " " + haha4)
            f_out.write(haha3 + " " + haha4)
            f_out.write("\n")
        line = f.readline()
    f.close()
    f_out.close()

    main()

    return redirect("main:result")

def result(request):
    return render(request,"result.html")

def about(request):
    return render(request,"about.html")

templates/about.html
{% extends "base.html" %}
{% block content %}
<h1>cesihi</h1>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<!-- Bootstrap CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
	<link href="{% static "styles.css" %}" rel="stylesheet">
    
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, inital-scale=1">

    <!-- Google fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Alegreya">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Quicksand">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Work+Sans">

    <title>Video cutter | UOFTHacks</title>
</head>

<body a link="black" vlink="black">
<!-- Bootstrap Bundle with Popper -->
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>

 <!-- navigation bar -->
 <header>
<<<<<<< HEAD
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<div class="container-fluid">
		<a class="navbar-brand" href="home.html">Lecture-Go</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
		</button>
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav me-auto mb-2 mb-lg-0">
			<li class="nav-item">
			<a class="nav-link active" aria-current="page" href="home.html">Home</a>
			</li>
			<li class="nav-item">
			<a class="nav-link" href="#">Link</a>
			</li>
			<li class="nav-item dropdown">
			<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
				Dropdown
			</a>
			<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
				<li><a class="dropdown-item" href="#">Action</a></li>
				<li><a class="dropdown-item" href="#">Another action</a></li>
				<li><hr class="dropdown-divider"></li>
				<li><a class="dropdown-item" href="#">Something else here</a></li>
=======
	<div class="container">
		<nav>
			<ul>
			 <li><a class= "nav-font" href = "{% url 'main:index' %}">Video Cutter</a></li>
			 <li><a class= "nav-font" href = "{% url 'main:about' %}">About</a></li>
>>>>>>> a6b4da679ddc90f9c07b06a5e6d89aa7292eee66
			</ul>
			</li>
			<li class="nav-item">
			<a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
			</li>
		</ul>
		<form class="d-flex">
			<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
			<button class="btn btn-outline-success" type="submit">Search</button>
		</form>
		</div>
	</div>
	</nav>
 </header>

<!-- Animated circles -->
 <div> 
 	<ul class="animated-circles">
 		<li></li>
 		<li></li>
 		<li></li>
 		<li></li>
 		<li></li>
 	</ul>
 </div>

 
 <section>

 	<h1> TEST ELEMENT </h1>




{% block content %}


{% endblock content %}


</section>




</body>
</html>

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}


  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
   <script>
function submitform() {
                $(".btn").attr("disabled", true);
                $("#spinner").show();
                $("#urlform").submit()
            }
</script>
    <meta charset="UTF-8">
    <div class="container-fluid col-lg-7">
    <div class="alert alert-primary" role="alert">
        <h1 style="text-align: center;">Time-saver</h1>
<form name="urlform" id="urlform" method="post"  action="{% url 'main:download' %}">
    {% csrf_token %}
<input class="form-control" type="text" name="urlname" placeholder="please input the URL of the video">
<br>
    <button class="btn btn-success" onclick="submitform()">Next</button> <div class="spinner-border" style="display: none" id="spinner" role="status"></div>



    </form>
    </div>
    </div>
{% endblock content %}

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lecture-go</title>
</head>
<body>
<h1>Hello World!</h1>
<form method="post" action="{% url 'main:download' %}">
    {% csrf_token %}
<input type="text" name="urlname" placeholder="please input the URL of the video">
<button type="submit">Submit</button>

    </form>
</body>
</html>

templates/result.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

</head>
<body>
 <div class="container-fluid col-lg-7" style="text-align: center">
    <div class="alert alert-primary" role="alert">
<h1>Hey,this is the cutted video! Enjoy</h1>
        <br>
<script type="text/javascript" src="{% static "ckplayer/ckplayer/ckplayer.js" %}" charset="utf-8" data-name="ckplayer"></script>
<div class="text-center">
        <div class="video" style="width: 600px;height: 400px;">container</div>
<script type="text/javascript">
    // from the official document of ckplayer
    //定义一个变量：videoObject，用来做为视频初始化配置
    var videoObject = {
        container: '.video', //“#”代表容器的ID，“.”或“”代表容器的class
        variable: 'player', //播放函数名称，该属性必需设置，值等于下面的new ckplayer()的对象
        video: '{% static "edited.mp4" %}'//视频地址
    };
    var player = new ckplayer(videoObject);//初始化播放器
</script>
    </div>
 </div>
     </div>
</body>
</html>

templates/success.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <meta charset="UTF-8">
    <title>Lecture-go</title>
</head>
<body>
<br>
<script>
     function showloading(url) {
                $(".btn").attr("disabled", true);
                $("#spinner").show();
                window.open(url,"_self");
            }
</script>
<div class="container-fluid">
    <div class="alert alert-success" role="alert">

<h1 style="text-align: center;"><svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-file-earmark-check" viewBox="0 0 16 16">
  <path d="M10.854 7.854a.5.5 0 0 0-.708-.708L7.5 9.793 6.354 8.646a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z"/>
  <path d="M14 14V4.5L9.5 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2zM9.5 3A1.5 1.5 0 0 0 11 4.5h2V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h5.5v2z"/>
</svg>Download success!
</h1>
        <br>
        <div style="text-align: center">
<button class="btn btn-success" onclick="showloading('{% url 'main:cut' %}')">Click me</button> to remove all silence.          <div class="spinner-border" style="display: none" id="spinner" role="status"></div>

</div>
        </div>
    </div>
<script type="text/javascript" src="{% static "ckplayer/ckplayer/ckplayer.js" %}" charset="utf-8" data-name="ckplayer"></script>
<div class="text-center">
        <div class="video" style="width: 600px;height: 400px;">container</div>
<script type="text/javascript">
    // from the official document of ckplayer
    //定义一个变量：videoObject，用来做为视频初始化配置
    var videoObject = {
        container: '.video', //“#”代表容器的ID，“.”或“”代表容器的class
        variable: 'player', //播放函数名称，该属性必需设置，值等于下面的new ckplayer()的对象
        video: '{% static "video.mp4" %}'//视频地址
    };
    var player = new ckplayer(videoObject);//初始化播放器
</script>
    </div>
 </div>
</body>
</html>